---
- name: Make sure baseline packages are installed
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present

- name: Ensure all packages are updated
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Make sure firewalld is enabled and runs
  ansible.builtin.systemd_service:
    name: firewalld
    enabled: true
    state: started

- name: Make sure chronyd is enabled and runs
  ansible.builtin.systemd_service:
    name: chronyd
    enabled: true
    state: started
